services:
  - type: web
    name: talent-ai
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m nltk.downloader punkt stopwords
    startCommand: streamlit run app/ui.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true

